---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:7

  - name: consul-01
    image: ubuntu:16.04

  - name: consul-02
    image: ubuntu:16.04

  - name: consul-03
    image: ubuntu:16.04

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - syntax
    - destroy
    - create
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
