---
# tasks file for consul

- name: Download consul zip
  get_url:
    url: https://releases.hashicorp.com/consul/0.8.5/consul_0.8.5_linux_amd64.zip
    dest: /etc/

- name: unzip downloaded folder
  command: unzip -o /etc/consul_0.8.5_linux_amd64.zip -d /usr/local/bin/
  register: ouput_unzip

- name: create systemd configuration for consul
  template:
    src: templates/consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0755

- name: create consul directory
  file:
    path: /etc/consul.d/
    state: directory
